spring:
  #DB Configuration:
  datasource:
    url: jdbc:mysql://192.168.13.48:3306/seckill?&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Sunstar123!
  redis:
    host: 192.168.13.48
  zipkin:
    sender:
      type: web
    base-url: http://192.168.13.48:9411
    enabled: true
    discoveryClientEnabled: true
  sleuth:
    sampler:
      probability: 1.0
  #监控
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  #log
logging:
  level:
    root: info
#mysql 日志
#logging.level.com.yimi.product.mapper=DEBUG

logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG

##很重要
#security:
#  oauth2:
#    resource:
#      filter-order: 3