pipeline{
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building eureka server'
                sh 'pwd'
                sh '''#!/bin/bash
                    cd eureka-server
                    echo 'in the sh file now'
                    pwd
                    '''
                sh 'pwd'
                sh 'whoami'
                sh 'ssh root@192.168.13.182  'ls''
            }
        }
        stage('Test') {
            steps{
                echo 'This is a test step'
            }
        }
        stage('docker') {
            steps{
                echo 'This is a docker step'
            }
        }
        stage('Deploy') {
            steps{
                echo 'This is a deploy step'
            }
        }
    }
}