pipeline{
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building eureka server'
                sh 'pwd'
                sh '''#!/bin/bash
                    cd eureka-server
                    echo 'in the sh file now'
                    pwd
                    '''
                sh 'pwd'
            }
        }
        stage('Test') {
            steps{
                echo 'This is a test step'
            }
        }
        stage('Deploy') {
            steps{
                echo 'This is a deploy step'
            }
        }
    }
}