pipeline{
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building eureka server to test env test master '
                sh 'pwd'
            }
        }
        stage('Test') {
            steps{
                echo 'This is a test step'
            }
        }
        stage('Deploy') {
            steps{
                echo 'This is a deploy step'
            }
        }
    }
}