
server:
  port: 8781
#注册中心的服务名
spring:
  application:
    name: zuul-server
  cloud:
    inetutils:
      preferred-networks:
        - 10.0
      ignored-interfaces:
        - eth0
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: zuul-server #约定和swarm服务名对应,其实没啥作用
    prefer-ip-address: true #注册中心,注册的是ip
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}


#是否开启重试功能
zuul:
  retryable: true
  #对当前服务的重试次数
ribbon:
  MaxAutoRetries: 0
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 1


  #监控
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  #log
logging:
  level:
    root: info
#mysql 日志
#logging.level.com.yimi.product.mapper=DEBUG

#路由规则