version: "3"
services:
  eureka1:      # 默认情况下，其他服务可以使用服务名称连接到该服务。因此，对于eurekaService1的节点，它需要连接http://eurekaService2/3:951X/eureka/，因此需要配置该服务的名称是eurekaService1。
    image: sunstardocker/eureka-server:0.0.3
    deploy:
      replicas: 1   #定义 replicated 模式的服务的复本数量
      update_config:
        parallelism: 1    #每次更新复本数量
        delay: 2s       #每次更新间隔
      restart_policy:
        condition: on-failure     #定义服务的重启条件
    networks:
    - eureka-net
    ports:
    - "8761:8761"
    environment:
    - spring.profiles.active=eureka1
  eureka2:    # 高可用eureka注册节点2
    image: sunstardocker/eureka-server:0.0.3
    deploy:
      replicas: 1   #定义 replicated 模式的服务的复本数量
      update_config:
        parallelism: 1    #每次更新复本数量
        delay: 2s       #每次更新间隔
      restart_policy:
        condition: on-failure     #定义服务的重启条件
    networks:
    - eureka-net
    ports:
    - "8762:8762"
    environment:
    - spring.profiles.active=eureka2
  eureka3:    # 高可用eureka注册节点3
    image: sunstardocker/eureka-server:0.0.3
    deploy:
      replicas: 1   #定义 replicated 模式的服务的复本数量
      update_config:
        parallelism: 1    #每次更新复本数量
        delay: 2s       #每次更新间隔
      restart_policy:
        condition: on-failure     #定义服务的重启条件
    networks:
    - eureka-net
    ports:
    - "8763:8763"
    environment:
    - spring.profiles.active=eureka3
networks:
  eureka-net:            #网络名称
    driver: overlay