
##监控
turbine:
  aggregator:
    clusterConfig: default # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    #表明监控哪些服务
  appConfig: movie-server
  clusterNameExpression: new String("default")



logging:
  level:
    root: info

#eureka客户端ribbon刷新时间
#默认30s
#ribbon:
#  ServerListRefreshInterval: 1000
