spring:
  application:
    name: eureka-server #用于注册到eureka的名称,消费服务根据这个名,获取生产者的overlay的ip和端口号
  cloud:
    inetutils:
      preferredNetworks: #使用以下ip开头
      - 10.0

##监控
turbine:
  aggregator:
    clusterConfig: default # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    #表明监控哪些服务
  appConfig: movie-server
  clusterNameExpression: new String("default")

server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server       #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/  #Eureka节点相互注册
#      register-with-eureka: true
#---
#server:
#  port: 8762
#spring:
#  profiles: eureka2
#eureka:
#  instance:
#    hostname: eureka2      #Eureka实例的主机名
#    #prefer-ip-address: true
#    #instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
#      register-with-eureka: true
#---
#server:
#  port: 8763
#spring:
#  profiles: eureka3
#eureka:
#  instance:
#    hostname: eureka3    #Eureka实例的主机名
#    #prefer-ip-address: true
#    #instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
#      register-with-eureka: true


