
server:
  port: 8771
#注册中心的服务名
spring:
  application:
    name: config-server
  cloud:
    inetutils:
      preferred-networks:
        - 10.0

    config:
      server:
        git:
          uri: http://192.168.13.183/sunstar/config-server.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: root                                   # git仓库的账号
          password: 7746595peter                                        # git仓库的密码
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.13.48
    port: 5672
    username: root
    password: 7746595

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: config-server #约定和swarm服务名对应,其实没啥作用
    prefer-ip-address: true #注册中心,注册的是ip
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

  #监控
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  #log
logging:
  level:
    root: info
#mysql 日志
#logging.level.com.yimi.product.mapper=DEBUG